#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

sudo apt-get install ufw
# ensure 
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw status
sudo ufw disable -y
sudo ufw enable -y
sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y
# allow incoming SSH connections so you can connect and manage your server
sudo ufw allow ssh
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
