#!/usr/bin/env bash
# Configure domains and subdomains:
# www 		--> 58428-lb-01 34.224.1.230
# web-01 	--> 58428-web-01 52.90.23.35
# web-02 	--> 58428-web-02 54.234.81.27

# define params
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain=$1
sub=$2

get_domain_information () {
	sub=$2
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		get_domain_information "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	get_domain_information "$domain" "$sub"
fi
