#!/usr/bin/env bash
# Configure webcronx.tech, subdomains to point to IP:
# www 		--> 58428-lb-01  54.164.52.24
# web-01 	--> 58428-web-01 54.208.255.120
# web-02 	--> 58428-web-02 52.201.211.133

# define params
subdomains_all=( "www" "lb-01" "web-01" "web-02" )

get_domain_information () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
	get_domain_information "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    get_domain_information "$subdomain" "$domain"
fi
