#!/usr/bin/env bash

function get_record() {
    local domain=$1
    local subdomain=$2

    if [[ -z $subdomain ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record=$(dig +short $sub.$domain)
        if [[ -n $record ]]; then
            echo "The subdomain $sub is a $(dig +short $sub.$domain | awk '{print $1}') record and points to $record"
        fi
    done
}

get_record "$@"
