#!/usr/bin/env bash
# transfer a file from our client to a server
# Accepts 4 parameters
# - The path to the file to be transferred
# - The IP of the server we want to transfer the file to
# - The username scp connects with
# - The path to the SSH private key that scp uses
# scp must transfer the file to the user home directory ~/
if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
