#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get update && sudo apt-get upgrade
sudo apt-get install nginx -y

# set firewall rule for Nginx HTTP
sudo ufw allow 'Nginx HTTP'

mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html
SERVER_CONFIG=\
"server {
	listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

	location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
    }
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi